# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>

development:
  # adapter: async
  adapter: redis
  url: redis://localhost:6379

test:
  adapter: async
